name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build ethier
        run: |
          go version
          go build -o ~/.local/bin/ethier ./ethier

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Setup Solidity tooling
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc abigen

      - name: Run tests
        run: npm run testverbose

      - name: Check solidity code style
        run: npx prettier '**/*.sol' --check

      - name: Check go code style
        run: test -z $(gofmt -l .)